# Generated by Django 3.2.6 on 2021-09-03 13:52

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('currency', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8, unique=True)),
                ('name', models.CharField(max_length=64, verbose_name='name')),
                ('is_active', models.BooleanField(default=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='currency.currency')),
            ],
            options={
                'unique_together': {('name', 'currency')},
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225, unique=True, verbose_name='name')),
                ('description', models.TextField(blank=True)),
                ('balance_limit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('status', models.CharField(choices=[('Active', 'Account is active and can be used to transfer money'), ('Opened', 'Account is opened but is not active yet'), ('Closed', 'Account is closed and cannot be active anymore'), ('Freeze', 'Account is inactive now but will be active or closed later')], default='Opened', max_length=8)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('date_activated', models.DateTimeField(blank=True)),
                ('date_closed', models.DateTimeField(blank=True)),
                ('account_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='account.accounttype')),
                ('other_users', models.ManyToManyField(related_name='secondary_accounts', to=settings.AUTH_USER_MODEL)),
                ('primary_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_accounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
