# Generated by Django 3.2.6 on 2021-09-05 18:02

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='balance_limit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Balance limit is 0.00 by default. Set to null, it means there is no limit for balance.', max_digits=4, null=True),
        ),
    ]
